# Generated by Django 2.2.5 on 2020-07-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200701_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_o', models.CharField(max_length=30, null=True)),
                ('email_o', models.CharField(max_length=50, null=True)),
                ('message_o', models.CharField(max_length=9000, null=True)),
                ('created_o', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
