# Generated by Django 2.2.5 on 2020-07-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_o',
        ),
    ]
